version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: currencx
      POSTGRES_PASSWORD: currencx
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    restart: unless-stopped

volumes:
  postgres: ~
